import { Dimensions, StyleSheet } from 'react-native';

const BRAND_BLUE = "#2DB6FF";
const BRAND_PINK = "#F47CC6";
const BRAND_GRAY = "#6C6C6C";

const { width: screenWidth } = Dimensions.get('window');

export const calendarStyles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 10,
    // backgroundColor is now dynamic from theme
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 12,
  },
  headerButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  viewAllButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0F8FF',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#007AFF',
    gap: 6,
  },
  viewAllButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#007AFF',
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    // color is now dynamic from theme
  },
  currentDate: {
    fontSize: 14,
    marginTop: 4,
    // color is now dynamic from theme
  },
  addButton: {
    backgroundColor: BRAND_BLUE,
    borderRadius: 20,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  calendarContainer: {
    marginBottom: 16,
  },
  // Event notification styles
  eventNotificationSection: {
    backgroundColor: '#F8F9FA',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  eventNotificationHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  eventNotificationTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  eventNotificationStatus: {
    marginBottom: 12,
  },
  eventNotificationStatusText: {
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 4,
  },
  eventNotificationTimestamp: {
    fontSize: 12,
    fontStyle: 'italic',
  },
  upcomingEventsInfo: {
    marginBottom: 12,
    padding: 12,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  upcomingEventsText: {
    fontSize: 14,
    fontWeight: '500',
    marginBottom: 4,
  },
  nextEventText: {
    fontSize: 13,
    fontStyle: 'italic',
  },
  refreshButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    gap: 6,
  },
  refreshButtonText: {
    fontSize: 13,
    fontWeight: '500',
  },
  // Toggle styles
  toggleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  toggleLabelContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  toggleSwitch: {
    width: 50,
    height: 28,
    backgroundColor: '#E0E0E0',
    borderRadius: 14,
    padding: 2,
    justifyContent: 'center',
  },
  toggleSwitchActive: {
    backgroundColor: BRAND_PINK,
  },
  toggleThumb: {
    width: 24,
    height: 24,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  toggleThumbActive: {
    transform: [{ translateX: 22 }],
  },
  toggleDescription: {
    fontSize: 12,
    lineHeight: 16,
    fontStyle: 'italic',
  },
  // Event alarmable styles
  eventAlarmableContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 'auto',
    paddingLeft: 8,
  },
  alarmableToggle: {
    marginLeft: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: '#F5F5F5',
  },
  alarmableToggleText: {
    fontSize: 11,
    fontWeight: '500',
  },
  daysOfWeek: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
    paddingHorizontal: 0,
  },
  dayOfWeek: {
    fontSize: 16,
    fontWeight: '600',
    width: ((screenWidth - 80) / 7),
    textAlign: 'center',
    // color is now dynamic from theme
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    paddingHorizontal: 0,
    width: '100%',
    alignContent: 'flex-start',
  },
  calendarDay: {
    width: ((screenWidth - 80) / 7),
    height: ((screenWidth - 80) / 7),
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 2,
    borderRadius: 0,
    backgroundColor: 'transparent',
    position: 'relative',
  },
  selectedDay: {
    backgroundColor: BRAND_PINK,
    borderRadius: 20,
  },
  dayNumber: {
    fontSize: 18,
    fontWeight: '500',
    // color is now dynamic from theme
  },
  selectedDayText: {
    color: '#FFFFFF',
  },
  todayDay: {
    backgroundColor: BRAND_BLUE,
    borderRadius: 20,
  },
  todayDayText: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  eventIndicator: {
    position: 'absolute',
    bottom: 4,
    right: 4,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: BRAND_PINK,
    zIndex: 1,
  },
  summaryContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 16,
    paddingVertical: 8,
    backgroundColor: 'transparent',
    borderRadius: 0,
  },
  summaryItem: {
    alignItems: 'center',
    flex: 1,
  },
  summaryContent: {
    alignItems: 'center',
  },
  summaryNumber: {
    fontSize: 18,
    fontWeight: '600',
    // color is now dynamic from theme
  },
  summaryLabel: {
    fontSize: 11,
    marginTop: 4,
    // color is now dynamic from theme
  },
  section: {
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 12,
    // color is now dynamic from theme
  },
  itemCard: {
    flexDirection: 'row',
    backgroundColor: 'transparent',
    borderRadius: 0,
    padding: 12,
    marginBottom: 8,
    alignItems: 'center',
    borderBottomWidth: 1,
    // borderBottomColor is now dynamic from theme
  },
  itemDateSquare: {
    width: 56,
    height: 56,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
    backgroundColor: BRAND_PINK,
  },
  itemDateText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  itemContent: {
    flex: 1,
  },
  itemTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 4,
    // color is now dynamic from theme
  },
  itemTime: {
    fontSize: 13,
    marginBottom: 3,
    // color is now dynamic from theme
  },
  itemPlace: {
    fontSize: 13,
    // color is now dynamic from theme
  },
  todoItem: {
    flexDirection: 'row',
    backgroundColor: 'transparent',
    borderRadius: 0,
    padding: 12,
    marginBottom: 8,
    alignItems: 'center',
    borderBottomWidth: 1,
    // borderBottomColor is now dynamic from theme
  },
  todoCheckbox: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: BRAND_GRAY,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
    backgroundColor: 'transparent',
  },
  todoCheckboxCompleted: {
    backgroundColor: BRAND_PINK,
    borderColor: BRAND_PINK,
  },
  todoContent: {
    flex: 1,
  },
  todoTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 2,
    // color is now dynamic from theme
  },
  todoTitleCompleted: {
    textDecorationLine: 'line-through',
    color: BRAND_GRAY,
  },
  todoDate: {
    fontSize: 12,
    // color is now dynamic from theme
  },
  todoDueDate: {
    fontSize: 12,
    marginTop: 4,
    // color is now dynamic from theme
  },
  todoPriority: {
    marginLeft: 10,
  },
  priorityBadge: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  priorityText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FFFFFF',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  noItemsContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
  },
  noItemsText: {
    textAlign: 'center',
    fontSize: 16,
    fontStyle: 'italic',
    marginTop: 16,
    // color is now dynamic from theme
  },
  modalContainer: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    paddingTop: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 24,
    paddingVertical: 20,
    borderBottomWidth: 2,
    borderBottomColor: '#F0F0F0',
    backgroundColor: '#FAFAFA',
  },
  closeButton: {
    padding: 12,
    borderRadius: 25,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#2D2D2D',
    textAlign: 'center',
    flex: 1,
    marginHorizontal: 16,
  },
  typeSelection: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 24,
    paddingHorizontal: 20,
    gap: 12,
  },
  typeButton: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#F0F0F0',
    backgroundColor: '#FFFFFF',
  },
  typeButtonSelected: {
    borderColor: BRAND_PINK,
    backgroundColor: BRAND_PINK,
  },
  typeButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#757575',
    marginTop: 8,
  },
  typeButtonTextSelected: {
    color: '#FFFFFF',
  },
  formContainer: {
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  formField: {
    marginBottom: 12,
  },
  formLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#424242',
    marginBottom: 8,
  },
  textInput: {
    borderWidth: 1,
    borderColor: '#F0F0F0',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: '#2D2D2D',
    backgroundColor: '#FFFFFF',
  },
  textArea: {
    minHeight: 80,
    paddingTop: 10,
    textAlignVertical: 'top',
  },
  dateTimeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  dateTimeInput: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    minHeight: 48,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
    justifyContent: 'space-between',
  },
  dateTimeText: {
    fontSize: 16,
    color: '#2D2D2D',
    textAlign: 'center',
    paddingVertical: 8,
    fontWeight: '500',
    flex: 1,
    textAlignVertical: 'center',
  },
  dateTimeTextInput: {
    flex: 1,
    fontSize: 16,
    color: '#2D2D2D',
    marginLeft: 10,
    padding: 0,
    justifyContent: 'center',
  },
  placeInputContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  placeInput: {
    flex: 1,
    fontSize: 16,
    color: '#2D2D2D',
    marginLeft: 10,
  },
  placeSuggestions: {
    marginTop: 8,
  },
  placeSuggestionsTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#666',
    marginBottom: 8,
  },
  placeSuggestionsList: {
    gap: 4,
  },
  placeSuggestionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    gap: 8,
  },
  placeSuggestionText: {
    fontSize: 14,
    color: '#2D2D2D',
  },
  placeSuggestionContent: {
    flex: 1,
    marginLeft: 8,
  },
  placeSuggestionSubtext: {
    fontSize: 12,
    color: '#666',
    marginTop: 2,
  },
  priorityContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
    gap: 8,
  },
  priorityButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#F0F0F0',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
  },
  priorityButtonSelected: {
    borderColor: '#FF5722',
    backgroundColor: '#FF5722',
  },
  priorityButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#757575',
  },
  priorityButtonTextSelected: {
    color: '#FFFFFF',
  },
  statusContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
    gap: 8,
  },
  statusButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#F0F0F0',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
  },
  statusButtonSelected: {
    borderColor: BRAND_PINK,
    backgroundColor: BRAND_PINK,
  },
  statusButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#757575',
  },
  statusButtonTextSelected: {
    color: '#FFFFFF',
  },
  imageUploadContainer: {
    alignItems: 'center',
    paddingVertical: 20,
    borderWidth: 2,
    borderColor: '#E0E0E0',
    borderStyle: 'dashed',
    borderRadius: 12,
    marginTop: 12,
    backgroundColor: '#FAFAFA',
  },
  imageUploadText: {
    fontSize: 14,
    marginTop: 10,
    // color is now dynamic from theme
  },
  imageButtonsContainer: {
    flexDirection: 'row',
    marginTop: 15,
    justifyContent: 'space-around',
  },
  imageButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 20,
  },
  imageButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
    marginLeft: 5,
  },
  uploadedImage: {
    width: 100,
    height: 100,
    borderRadius: 8,
    marginBottom: 10,
  },
  detailsContainer: {
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  detailsTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#2D2D2D',
    marginBottom: 10,
    textAlign: 'center',
  },
  detailsInfo: {
    marginBottom: 24,
    backgroundColor: '#F8F9FA',
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: '#E9ECEF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#F1F3F4',
  },
  detailText: {
    fontSize: 16,
    color: '#2D2D2D',
    marginLeft: 16,
    fontWeight: '600',
    flex: 1,
  },
  actionButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 24,
    gap: 16,
    paddingHorizontal: 4,
  },
  editButton: {
    backgroundColor: BRAND_PINK,
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    flex: 1,
    shadowColor: BRAND_PINK,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
    borderWidth: 2,
    borderColor: BRAND_PINK,
  },
  editButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FFFFFF',
    marginLeft: 8,
    textAlign: 'center',
  },
  deleteButton: {
    backgroundColor: '#FF4757',
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    flex: 1,
    shadowColor: '#FF4757',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
    borderWidth: 2,
    borderColor: '#FF4757',
  },
  deleteButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FFFFFF',
    marginLeft: 8,
    textAlign: 'center',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    // backgroundColor is now dynamic from theme
  },
  loadingText: {
    marginTop: 16,
    // color is now dynamic from theme
  },
  saveButtonContainer: {
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  saveButton: {
    borderRadius: 12,
    overflow: 'hidden',
    marginHorizontal: 20,
  },
  saveButtonGradient: {
    paddingVertical: 18,
    alignItems: 'center',
    borderRadius: 12,
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  statusBadge: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  statusText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FFFFFF',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  detailsImage: {
    width: '100%',
    height: 220,
    borderRadius: 16,
    marginTop: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  descriptionSection: {
    marginTop: 24,
    marginBottom: 24,
    backgroundColor: '#F8F9FA',
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: '#E9ECEF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  descriptionText: {
    fontSize: 16,
    color: '#2D2D2D',
    lineHeight: 24,
    textAlign: 'justify',
    fontWeight: '500',
  },
  prioritySection: {
    marginTop: 15,
  },
  statusSection: {
    marginTop: 15,
  },
  imageSection: {
    marginTop: 24,
    marginBottom: 24,
    backgroundColor: '#F8F9FA',
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: '#E9ECEF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  pastItemCard: {
    opacity: 0.7,
    backgroundColor: '#F5F5F5',
  },
  pastItemTitle: {
    color: '#757575',
  },
  pastItemText: {
    color: '#9E9E9E',
  },
  completedTodoItem: {
    opacity: 0.8,
    backgroundColor: '#F0F8F0',
    borderColor: '#4CAF50',
  },
  pickerButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    paddingVertical: 16,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
  },
  pickerButton: {
    backgroundColor: BRAND_BLUE,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pickerButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  pickerOverlay: {
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
    paddingTop: 16,
    marginTop: 16,
  },
  customPickerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  customPickerContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    width: '90%',
    maxHeight: '80%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  customPickerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  customPickerTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#2D2D2D',
  },
  customPickerCloseButton: {
    padding: 8,
  },
  customPickerContent: {
    padding: 20,
  },
  monthSelector: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  monthButton: {
    padding: 8,
  },
  monthText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#2D2D2D',
  },
  customPickerDaysOfWeek: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  customPickerDayOfWeek: {
    fontSize: 14,
    fontWeight: '600',
    color: '#757575',
    width: 40,
    textAlign: 'center',
  },
  customPickerGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
  },
  customPickerDay: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    margin: 2,
    borderRadius: 20,
    backgroundColor: 'transparent',
  },
  customPickerSelectedDay: {
    backgroundColor: BRAND_PINK,
  },
  customPickerTodayDay: {
    backgroundColor: BRAND_BLUE,
  },
  customPickerDayNumber: {
    fontSize: 16,
    fontWeight: '500',
    color: '#424242',
  },
  customPickerSelectedDayText: {
    color: '#FFFFFF',
  },
  customPickerTodayDayText: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  customPickerEmptyDay: {
    width: 40,
    height: 40,
    margin: 2,
  },
  timeSelector: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  timeColumn: {
    flex: 1,
    alignItems: 'center',
  },
  timeLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2D2D2D',
    marginBottom: 12,
  },
  timeScrollView: {
    maxHeight: 200,
  },
  timeOption: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginVertical: 2,
    minWidth: 60,
    alignItems: 'center',
  },
  timeOptionSelected: {
    backgroundColor: BRAND_BLUE,
  },
  timeOptionText: {
    fontSize: 16,
    color: '#424242',
  },
  timeOptionTextSelected: {
    color: '#FFFFFF',
    fontWeight: '600',
  },
  timeConfirmButton: {
    backgroundColor: BRAND_PINK,
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 20,
    alignItems: 'center',
    alignSelf: 'center',
  },
  timeConfirmButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  detailsHeader: {
    alignItems: 'center',
    marginBottom: 28,
    paddingVertical: 20,
    backgroundColor: '#FAFAFA',
    borderRadius: 20,
    marginHorizontal: 4,
  },
  detailsIconContainer: {
    width: 90,
    height: 90,
    borderRadius: 45,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 8,
    borderWidth: 3,
    borderColor: '#FFFFFF',
  },
  todoDetailsSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
    gap: 16,
  },
  detailSection: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: '#F8F9FA',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E9ECEF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  detailSectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#424242',
    marginBottom: 12,
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
});

export { BRAND_BLUE, BRAND_GRAY, BRAND_PINK };

